#
# See file CREDITS for list of people who contributed to this
# project.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
obj-$(CONFIG_PHY_AIROHA_EN8811H) += an8811h/
obj-y += ecnt_eth.o
obj-y += ecnt_eth_phy.o
obj-y += skbuff.o
obj-y += tcswitch.o
obj-$(CONFIG_ECNT_MULTIUPGRADE) += multiupgrade.o

